In [1]:
# !pip install numpy  ->if numpy is not installed
import numpy as np


In [3]:
print(np.__version__)    # to see version

1.24.3


In [5]:
# Converting into numpy array.
# numpy array contains only numerical data.

l=[1,2,3,4,5,6,7,8,9,10]
np_array=np.array(l)     # numpy array is used for computation but normal array used to store data
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# Operation on numpy array
print(np_array+5)
print(np_array*5)
print(np_array/5)
print(np_array-5)
print(np_array%5)
print(np_array//5)

[ 6  7  8  9 10 11 12 13 14 15]
[ 5 10 15 20 25 30 35 40 45 50]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]
[-4 -3 -2 -1  0  1  2  3  4  5]
[1 2 3 4 0 1 2 3 4 0]
[0 0 0 0 1 1 1 1 1 2]


In [10]:
# Shape of array 
# kati dimention ko array ho vanera herne
print(np_array.shape)

(10,)


In [12]:
l=[[1,2,3],
   [4,5,6],
   [7,8,9]]
np_array=np.array(l)
print(np_array.shape)    #(3,3)  row and column
print(np_array.dtype)    # int32    integer data type  32 bit

(3, 3)
int32


In [14]:
l=[[[1],[2],[3]],
   [[4],[5],[6]],
   [[7],[8],[9]]]
np_array=np.array(l)
print(np_array.shape)   
print(np_array.dtype)    

(3, 3, 1)
int32


In [ ]:
# need Symmetric data ie:
#l=[[1,2,3],
#  [4,5],          invalid
#  [7,8,9]]

In [16]:
# Creating matrix of 0 and 1

print(np.zeros((3,3)))
print(np.ones((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# Reshaping array
l=[[1,2,3],
   [4,5,6]]
np_array=np.array(l)
np_array.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
# 6->2*3
# 6->3*2
# 6->1*6
# 6->6*1
print(np_array.reshape(3,2))
print(np_array.reshape(2,3))
print(np_array.reshape(1,6))
print(np_array.reshape(6,1))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [23]:
# Flatten array
# Converting into 1 dimentional array
np_array.flatten()

array([1, 2, 3, 4, 5, 6])

In [25]:
# For concatinating one or more numpy array
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([3,2,1,3,2,1,3,2,1])
print(a+b)    # This wont concatinate. It will perform numerical addition operation. So np.hstack() and np.vstack() are used.

[ 4  4  4  7  7  7 10 10 10]


In [26]:
# np.hstack()
# Horizontally concatinating two or more numpy array
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 2, 1, 3, 2, 1, 3, 2, 1])

In [27]:
# np.vstack()
# Vertically concatinating two or more numpy array
np.vstack((a,b))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [3, 2, 1, 3, 2, 1, 3, 2, 1]])

In [28]:
# Make matrix with random element.
# Random integer between [0,10) of shape(2,2)
print(np.random.randint(0,10,size=[2,2]))

[[7 2]
 [8 5]]


In [29]:
# Random integer between [0,256) of shape(8,8)
print(np.random.randint(0,256,size=[8,8]))

[[106 175 248 154 171  62  62  66]
 [252  26 255 173 144  55 183 163]
 [222  45 216  49  58 221  19 170]
 [154 176  65 244 225  85   6 221]
 [ 27  96 142  69  60 252  40  28]
 [ 79 153 203   2  78 244  60 183]
 [132 133   8 186 198  56 171  48]
 [111  80 128 122 249 228   1  83]]


In [32]:
# Pick 10 items from a given list with equal probability
print(np.random.choice(['a','e','i','o','u'],size=[2,2]))
print(np.random.choice(['a','e','i','o','u'],size=10))

[['i' 'u']
 ['i' 'e']]
['i' 'e' 'a' 'u' 'e' 'o' 'i' 'e' 'e' 'e']


In [37]:
# Pick 10 items from a given list with given probability
print(np.random.choice(['a','e','i','o','u'],size=10,p=[0.3,0.1,0.1,0.4,0.1]))

['u' 'a' 'o' 'o' 'u' 'a' 'a' 'o' 'u' 'a']
